site_name: tkintertools # ç«™ç‚¹åç§°
site_url: https://Xiaokang2022.github.io/tkintertools-docs # ç«™ç‚¹é“¾æ¥
repo_url: https://github.com/Xiaokang2022/tkintertools-docs # ä»“åº“åœ°å€
repo_name: Xiaokang2022/tkintertools-docs # ä»“åº“åç§°
edit_uri: edit/main/3.0/ # ç¼–è¾‘åœ°å€ï¼ˆé¡µé¢ä¼šå‡ºç°ç¼–è¾‘æŒ‰é’®ï¼‰
site_description: Official documentation website of tkintertools # ç«™ç‚¹æè¿°
site_author: Xiaokang2022 # ç«™ç‚¹ä½œè€…
copyright: Copyright &copy; 2022 Xiaokang2022 # ç‰ˆæƒä¿¡æ¯ï¼ˆä¼šå‡ºç°åœ¨å·¦ä¸‹è§’ï¼‰
remote_branch: gh-pages # GitHub Pages åˆ†æ”¯åç§°ï¼ˆæ­¤å¤„ä¸ºé»˜è®¤å€¼ï¼‰
remote_name: origin # è¿œç¨‹åˆ†æ”¯çš„åç§°ï¼ˆé»˜è®¤å€¼ï¼‰
docs_dir: 3.0/ # æ–‡æ¡£ç›®å½•ï¼ˆé»˜è®¤å€¼ï¼‰
site_dir: site # ç½‘ç«™ç›®å½•ï¼ˆé»˜è®¤å€¼ï¼‰
strict: false # ä¸¥æ ¼æ¨¡å¼ï¼Œä¸å¤ªæ‡‚ï¼ˆé»˜è®¤å€¼ï¼‰
dev_addr: 127.0.0.1:8000 # å¼€å‘æ¨¡å¼ä¸‹çš„ IP åœ°å€ï¼ˆé»˜è®¤å€¼ï¼‰

markdown_extensions:
  # === ä»è¿™é‡Œå¼€å§‹åˆ°ä¸‹é¢ï¼Œæ˜¯ pymdown-extensions åº“çš„ markdown_extensions é…ç½® ===
  # éœ€æ±‚ï¼špip install pymdown-extensions ï¼ˆä¸è¿‡ä¸€èˆ¬åº”è¯¥éƒ½è£…äº†ï¼‰

  - pymdownx.keys # æŒ‰é”®é«˜äº®ï¼Œç±»ä¼¼äºè¡Œå†…ä»£ç é‚£ç§ï¼Œå¦‚ <kbd>Ctrl</kbd>ï¼Œæˆ–è€…å¸¦å›¾æ ‡çš„æ ¼å¼ï¼ˆå¼ºåˆ¶å°å†™ï¼‰++ctrl++ï¼Œä¹Ÿå¯ç»„åˆ ++ctrl+s++ï¼ˆæ¨èç¬¬äºŒç§æ–¹å¼ï¼Œç¬¬äºŒç§è‡ªå¸¦å›¾æ ‡ï¼‰
  - pymdownx.mark # å…è®¸æ–‡æœ¬ä¸‹åˆ’çº¿ï¼Œå³ ^^Text^^
  - pymdownx.caret # å…è®¸æ–‡æœ¬é«˜äº®ï¼Œå³ ==Text==
  - pymdownx.tilde # å…è®¸æ–‡æœ¬åˆ é™¤çº¿ï¼Œå³ ~~Text~~
  - pymdownx.details # å…è®¸æç¤ºæ¡†ä¸æ–‡æœ¬å·¦å³å¸ƒå±€ï¼Œè€ŒéåŸæ¥çš„ä¸Šä¸‹å¸ƒå±€ï¼Œå¦‚ !!! note inline "Hint"ï¼ˆå·¦ï¼‰ï¼Œ!!! note inline endï¼ˆå³ï¼‰
  - pymdownx.snippets # å…è®¸å¤–è”ä»»ä½•å†…å®¹
  - pymdownx.striphtml # å»é™¤ HTML ä¸­ä¸éœ€è¦çš„æ³¨é‡Šå’Œ / æˆ–æ ‡è®°å±æ€§ï¼Œå¯å‡å° HTML å¤§å°
  - pymdownx.smartsymbols # å…è®¸ä¸Šä¸‹æ ‡ï¼Œå¦‚ x^2^ï¼ˆxÂ²ï¼‰
  - pymdownx.inlinehilite # æ”¯æŒè¡Œå†…ä»£ç å—é«˜äº®ï¼Œå¦‚ `#!python range()`
  - pymdownx.smartsymbols # æ™ºèƒ½ç¬¦å·ï¼Œå¦‚ (c) å°±æ˜¯ Â©ï¸

  - pymdownx.b64 # å…è®¸ä½¿ç”¨ base64 ç¼–ç åµŒå…¥æœ¬åœ° PNGã€JPEG å’Œ GIF å›¾åƒå¼•ç”¨ï¼ˆpymdownx æ”¯æŒï¼Œmkdocs æš‚æ—¶ä¸æ”¯æŒï¼‰
  - pymdownx.escapeall # å…è®¸ä½¿ç”¨åæ–œæ ï¼ˆpymdownx æ”¯æŒï¼Œmkdocs è²Œä¼¼éƒ¨åˆ†æ”¯æŒï¼Œä¸å®Œå…¨æ”¯æŒï¼‰
  - pymdownx.magiclink # è‡ªåŠ¨è¯†åˆ«è¶…é“¾æ¥ï¼ˆpymdownx æ”¯æŒï¼Œmkdocs æš‚æ—¶ä¸æ”¯æŒï¼‰
  - pymdownx.progressbar # å…è®¸è¿›åº¦æ¡è¯­æ³•ï¼ˆpymdownx æ”¯æŒï¼Œmkdocs æš‚æ—¶ä¸æ”¯æŒï¼‰
  - pymdownx.saneheaders # â€œ#titleâ€ ä¹Ÿæ˜¯æ ‡é¢˜ï¼Œè™½ç„¶ä¸­é—´æ²¡æœ‰ç©ºæ ¼ï¼ˆpymdownx æ”¯æŒï¼Œmkdocs æš‚æ—¶ä¸æ”¯æŒï¼‰

  - pymdownx.blocks.tab # æ”¯æŒæ›´é«˜çº§çš„æ ‡ç­¾å—å†™æ³•ï¼ˆå±ï¼šå¯èƒ½ä¸ pymdownx.tabbed å†²çªï¼‰
  - pymdownx.blocks.html # æ”¯æŒä¸€äº›æ›´é«˜çº§çš„ md å†…åµŒ HTML è¯­æ³•ï¼ˆpymdownx.blocks é»˜è®¤å¼€å¯ï¼‰
  - pymdownx.blocks.details # æ”¯æŒæ›´é«˜çº§çš„æç¤ºæ¡†å¸ƒå±€ï¼ˆå±ï¼šå¯èƒ½ä¸ pymdownx.details å†²çªï¼‰
  - pymdownx.blocks.admonition # æ”¯æŒæ›´é«˜çº§æç¤ºæ¡†è¯­æ³•ï¼ˆå±ï¼šå¯èƒ½ä¸ admonition å†²çªï¼‰
  - pymdownx.blocks.definition # æ”¯æŒæ›´é«˜çº§çš„å®šä¹‰å—è¯­æ³•ï¼ˆå±ï¼šå¯èƒ½ä¸ def_listï¼‰

  - pymdownx.arithmatex: # å…è®¸æ•°å­¦è¡¨è¾¾å¼ï¼Œå³ $$y=x+1$$ï¼Œæˆ–è¡Œå†…çš„ $x=1$
      generic: true

  - pymdownx.betterem: # å…è®¸æ–œä½“å’ŒåŠ ç²—
      smart_enable: all

  - pymdownx.critic: # å…è®¸æ‰¹æ³¨ï¼Œæ‰¹æ³¨è¯¦æƒ…è§ https://mkdoc-material.llango.com/reference/formatting/
      mode: view # æ‰¹æ³¨æ¨¡å¼ï¼Œå¯ä¸º viewï¼Œaccept å’Œ rejectï¼Œä¸æ‡‚å¹²å•¥çš„

  - pymdownx.highlight: # å…è®¸ä»£ç å—è¯­æ³•é«˜äº®
      use_pygments: true # ä½¿ç”¨ pygments è€Œä¸æ˜¯ javascriptï¼Œå•¥æ„æ€ä¸æ‡‚
      linenums: true # å…¨éƒ¨æ˜¾ç¤ºè¡Œå·ï¼Œè‹¥ä¸º falseï¼Œä¹Ÿå¯æŒ‡å®šèµ·å§‹è¡Œå·ï¼Œå¦‚ ```python linenums="2"ï¼Œä¹Ÿå¯æŒ‡å®šé«˜äº®è¡Œï¼Œå¦‚ hl_lines="2-3"
      linenums_style: pymdownx-inline # è¡Œå·æ ·å¼ pymdownx-inline æˆ–è€… inline å’Œ tableï¼ˆæœ€å¥½ä¸è¦ä½¿ç”¨å…¶å®ƒçš„å€¼ï¼Œä¼šæœ‰ bugï¼Œå¦‚ä»£ç å¤åˆ¶æŒ‰é’®é”™ä½ï¼‰
      anchor_linenums: true # ç”¨é”šé“¾æ¥åŒ…è£…ä»£ç è¡Œå·ï¼Œä¾¿äºè¶…é“¾æ¥å’Œå…±äº«ï¼ˆå°±æ˜¯è¡Œå·å¯ä»¥åƒé”šç‚¹ä¸€æ ·è¢«ç‚¹å‡»ï¼‰
      line_spans: __span # è¿™å¯¹äºè¡Œçªå‡ºæ˜¾ç¤ºç­‰åŠŸèƒ½æ­£å¸¸å·¥ä½œè‡³å…³é‡è¦ï¼Œä¸æ‡‚
      pygments_lang_class: true # å¯¹äºè‡ªå®šä¹‰æ³¨é‡Šæ ‡è®°çš„åŠŸèƒ½è‡³å…³é‡è¦ï¼Œä¸æ‡‚
      # auto_title: true # è‡ªåŠ¨ä¸ºæ‰€æœ‰ä»£ç å—æ·»åŠ ä¸€ä¸ªæ ‡é¢˜

  - pymdownx.emoji: # å…è®¸ Emoji è¡¨æƒ…
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences: # å…è®¸å„ç§åµŒå¥—
      custom_fences:
        - name: mermaid # å…è®¸ mermaid å›¾è¡¨è¯­æ³•
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # ä¸æ¸…æ¥šå¹²å•¥çš„


  - pymdownx.tabbed: # å…è®¸å—ï¼ˆå¦‚ä»£ç å—ï¼‰æ·»åŠ æ ‡ç­¾ï¼Œå®ç°å¤šè¯­è¨€ç­‰æ•ˆæœ
      alternate_style: true # å”¯ä¸€æ”¯æŒçš„æ ·å¼ï¼Œä¸æ‰“å¼€ç­‰äºç”¨ä¸äº†
      combine_header_slug: true # åé¢çš„ä¸çŸ¥é“å¹²å•¥çš„
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.tasklist: # å…è®¸ Todo åˆ—è¡¨æ¸…å•
      custom_checkbox: true # å…è®¸ä¿®æ”¹å…¶æ ·å¼ï¼Œä¸ç„¶ç”¨é»˜è®¤æ ·å¼å°±å¾ˆä¸‘
      clickable_checkbox: true # æ˜¯å¦å¯é€šè¿‡ç‚¹å‡»åˆ‡æ¢çŠ¶æ€ï¼ˆä½†æ— å®é™…æ›´æ”¹ï¼Œåªæœ‰è§†è§‰æ•ˆæœï¼‰

  # === ä»è¿™é‡Œå¼€å§‹åˆ°ä¸‹é¢ï¼Œæ˜¯ Python-Markdownï¼ˆMkDocs é»˜è®¤çš„ï¼‰ çš„ markdown_extensions é…ç½® ===

  - meta # å…è®¸å…ƒæ ‡è®°ï¼Œé¡µé¢æºä»£ç é¡¶ä¸Šé‚£å‡ è¡Œè¢«æ¨ªçº¿ä¿ä½çš„å†…å®¹å°±æ˜¯å…ƒæ ‡è®°ï¼Œä¸ºäº†æ”¯æŒæŸäº›åŠŸèƒ½ä½¿ç”¨
  - abbr # å…è®¸æ–‡æœ¬æ‚¬æµ®æç¤ºï¼Œå°±æ˜¯ ToolTipï¼Œä¾‹å¦‚ï¼š*[Text]: å•Šå§å•Šå§
  - tables # å…è®¸ç”¨ç®€å•è¯­æ³•åˆ›å»ºè¡¨æ ¼
  - smarty # è²Œä¼¼æ˜¯ä¸ºäº†æé«˜å…¼å®¹æ€§çš„ï¼Œä¸å¤ªæ¸…æ¥š
  - def_list # å…è®¸â€œå®šä¹‰åˆ—è¡¨â€çš„è¯­æ³•ï¼Œè¯¦ç»†è§ https://mkdoc-material.llango.com/reference/lists/
  - attr_list # å…è®¸ç»™ md å…ƒç´ å¢åŠ  HTML å’Œ CSS å±æ€§ï¼Œå¦‚ä¸€ä¸ªæŒ‰é’® [Subscribe to our mailing list](#){: .md-button }ï¼Œç”šè‡³å›¾æ ‡ï¼Œè¯¦ç»†è§ https://mkdoc-material.llango.com/reference/buttons/
  - wikilinks # æ”¯æŒå¿«æ·é“¾æ¥è¯­æ³•ï¼Œä¾‹å¦‚ [[a link]]ï¼Œä¼šå˜æˆ ./a_link/
  - admonition # å…è®¸å„ç§å„æ ·çš„æç¤ºæ¡†ï¼Œæˆ–ä»£ç æ¡†ï¼Œæ ·å¼è§ https://mkdoc-material.llango.com/reference/admonitions/
  - md_in_html # å…è®¸ md å†…åµŒåœ¨ HTML ä¸­
  - sane_lists # ç†æ™ºåˆ—è¡¨ï¼Œé¿å…æ—§ç‰ˆ md æŠ½é£ï¼ˆå¼ºçƒˆæ¨èå¼€å¯ï¼‰
  # - nl2br # æ¢è¡Œç¬¦ç¡¬æ–­è£‚ï¼Œå³æ–‡æœ¬ä¸åƒæ—§ç‰ˆ md é‚£æ ·ï¼Œå¯ä»¥ç›´æ¥æ¢è¡Œ
  # - codehilite # è¢« pymdownx ç›¸å…³æ‰©å±•å–ä»£äº†ï¼Œä¸å»ºè®®ä½¿ç”¨è¿™ä¸ª
  # - fenced_code # è¢« pymdownx ç›¸å…³æ‰©å±•å–ä»£äº†ï¼Œä¸å»ºè®®ä½¿ç”¨è¿™ä¸ª

  - footnotes: # å…è®¸è„šæ³¨
      BACKLINK_TITLE: è¿”å›è„šæ³¨ {} # åº•éƒ¨è„šæ³¨çš„æç¤ºè¯ï¼Œå»ºè®®æ”¹ä¸€ä¸‹ï¼Œé»˜è®¤æ˜¯è‹±æ–‡çš„
      # SUPERSCRIPT_TEXT: {} # è„šæ³¨åç§°ï¼Œé»˜è®¤å°±æ˜¯ {}ï¼Œè¡¨ç¤ºæ ‡å·

  - toc: # ç›®å½•è®¾ç½®
      title: ç›®å½• # åœ¨å³ä¾§å¯¼èˆªä¾§è¾¹æ ä¸­è®¾ç½®ç›®å½•çš„æ ‡é¢˜
      permalink_title: ç‚¹å‡»å®šä½åˆ°é”šç‚¹ # è®¾ç½®é”šç‚¹é“¾æ¥çš„æç¤ºè¯
      permalink: "#" # å¯ç”¨ç›®å½•é”šç‚¹ï¼Œå¹¶è®¾ç½®ç¬¦å·ä¸º â€œ#â€
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # è¿™å•¥ç©æ„å„¿ï¼Œä¸æ‡‚ï¼ŒæŠ„å®˜ç½‘çš„
        kwds:
          case: lower

theme: # ä¸»é¢˜è®¾ç½®
  name: material # ç¬¬ä¸‰æ–¹ä¸»é¢˜åç§°
  custom_dir: 3.0/overrides # è¦†ç›–éƒ¨åˆ†åŸæ¥çš„ä¸»é¢˜ï¼ˆé‡è½½ç›®å½•ï¼‰
  language: zh # material è¯­è¨€
  features:
    # - header.autohide # é¡¶æ è‡ªåŠ¨éšè—
    - content.tooltips # æç¤ºæ¡†ï¼ˆä»¥å‰æœ‰çš„æ ·å¼å˜å¥½çœ‹äº†ï¼Œæ­¤å¤–è¿˜æ”¯æŒæ›´é«˜çº§çš„æç¤ºæ¡†è¯­æ³•ï¼‰
    - content.code.copy # ä¾‹å¦‚ï¼š``` python { .yaml .copy } é»˜è®¤å¼€å¯ï¼Œ{ .yaml .no-copy } å…³é—­
    - content.code.annotate # å…è®¸å†…è”ä»£ç æ³¨é‡Š
    - content.tabs.link # åŒæ ·çš„æ ‡ç­¾ï¼Œæ•´ä¸ªç½‘ç«™çš„åŒæ­¥åˆ‡æ¢ï¼Œå¦‚ C -> C++ï¼Œåˆ™å…¶å®ƒç±»ä¼¼çš„å…¨éƒ¨æ ‡ç­¾éƒ½åŒæ­¥åˆ‡æ¢
    - content.action.edit # å…è®¸é¡µé¢è¢«ç¼–è¾‘ï¼ˆä¼šå‡ºç°ç¼–è¾‘æŒ‰é’®ï¼‰
    - content.action.view # å…è®¸æŸ¥çœ‹é¡µé¢çš„æºä»£ç ï¼ˆä¼šå‡ºç°æŸ¥çœ‹æºä»£ç æŒ‰é’®ï¼‰
    - announce.dismiss # å…¬å‘Šæ å¯ä»¥è¢«å…³é—­
    # - navigation.expand # å·¦ä¾§è¾¹æ èŠ‚ç‚¹é»˜è®¤å…¨éƒ¨å±•å¼€ï¼ˆä¸ navigation.prune ä¸å…¼å®¹ï¼‰
    # - navigation.prune # å·¦ä¾§æ èŠ‚ç‚¹è‡³å¤šå±•å¼€ä¸€ä¸ªï¼Œä»¥æ­¤æ¥å‡å°ç«™ç‚¹çš„æ„å»ºå¤§å°ï¼ˆå¯¹äºé¡µæ•°100+çš„ç½‘ç«™å¾ˆæœ‰ç”¨ï¼Œä½†æ˜¯ï¼ä¸ navigation.expand ä¸å…¼å®¹ï¼‰
    - navigation.tabs # é¡µé¢é¡¶éƒ¨å¯¼èˆªæ 
    - navigation.footer # é¡µé¢åº•ä¸‹æ¢é¡µçš„æ”¯æŒ
    - navigation.indexes # å·¦ä¾§è¾¹æ å¤§èŠ‚ç‚¹æ˜¯å¦å¯ä»¥è¢«å¯¼å‘åˆ° index.md
    - navigation.instant # é¡µé¢ä¸ä¼šé‡å¤åŠ è½½ï¼ˆå·²åŠ è½½é¡µé¢ä¸ä¼šå†æ¬¡åŠ è½½ï¼‰
    - navigation.instant.progress # åŠ è½½é€Ÿåº¦æ…¢æ—¶ï¼Œåœ¨é¡µé¢é¡¶éƒ¨æ˜¾ç¤ºåŠ è½½è¿›åº¦ï¼ˆ400ms ä»¥ä¸ŠåŠ è½½æ—¶é—´æ‰ä¼šæ˜¾ç¤ºå®ƒï¼‰
    # - navigation.tabs.sticky # å¯¼èˆªæ æ ‡é¢˜æ ä½ç½®å›ºå®š
    # - navigation.sections # å·¦ä¾§è¾¹æ èŠ‚ç‚¹æ˜¯å¦ä¿æŒå±•å¼€
    - navigation.top # å›åˆ°é¡¶éƒ¨çš„æŒ‰é’®
    - navigation.tracking # é”šç‚¹è·Ÿè¸ª
    - search.share # æœç´¢æ åˆ†äº«æŒ‰é’®
    - search.suggest # æœç´¢æ å†…å®¹å»ºè®®
    - search.highlight # æœç´¢æ å†…å®¹é«˜äº®
    - toc.follow # é”šç‚¹å…³æ³¨ï¼Œä¾§è¾¹æ è‡ªåŠ¨æ»šåŠ¨ï¼Œä½¿é”šç‚¹æ€»æ˜¯å¯è§
    # - toc.integrate # å³è¾¹ä¾§æ æ˜¯å¦é›†æˆåˆ°å·¦ä¾§è¾¹æ 
  palette: # ç•Œé¢æ•´ä½“æ ·å¼
    - media: "(prefers-color-scheme)" # ç³»ç»Ÿä¸»é¢˜
      toggle: # åˆ‡æ¢æŒ‰é’®
        icon: material/theme-light-dark # å›¾æ ‡
        name: åˆ‡æ¢è‡³æ˜äº®ä¸»é¢˜ # æç¤ºè¯
    - media: "(prefers-color-scheme: light)" # äº®è‰²ä¸»é¢˜
      scheme: default
      # primary: grey # æ ‡é¢˜æ é¢œè‰²ï¼ˆå»ºè®®è‡ªå®šä¹‰ CSS è°ƒæ•´ï¼Œå› ä¸º footer ä¸ä¼šè¢«æ­¤å‚æ•°å½±å“ï¼ï¼‰
      accent: purple # é“¾æ¥é«˜äº®é¢œè‰²
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æš—é»‘ä¸»é¢˜
    - media: "(prefers-color-scheme: dark)" # æš—è‰²ä¸»é¢˜
      scheme: slate
      primary: black
      # accent: yellow
      toggle:
        icon: material/weather-night
        name: åˆ‡æ¢è‡³ç³»ç»Ÿä¸»é¢˜
  font: false # é¿å…ä»è°·æ­ŒåŠ è½½å­—ä½“å¯¼è‡´ç½‘é¡µåŠ è½½å˜æ…¢ï¼ˆå…·ä½“å‚æ•°å¯ä»¥åœ¨è‡ªå®šä¹‰ CSS ä¸­æŒ‡å®šï¼‰
  logo: logo.png # é¡µé¢å·¦ä¸Šè§’å¾½æ ‡
  favicon: logo.png # ç½‘é¡µçš„å›¾æ ‡
  icon: # å›¾æ ‡é‡è½½ï¼Œæ›¿æ¢æ‰é»˜è®¤çš„å›¾æ ‡
    previous: fontawesome/solid/angle-left # å·¦ä¸‹è§’å‘å‰ç¿»é¡µçš„å›¾æ ‡
    next: fontawesome/solid/angle-right # å³ä¸‹è§’å‘åç¿»é¡µçš„å›¾æ ‡
    repo: fontawesome/brands/github # å³ä¸Šè§’ä»“åº“å›¾æ ‡
    edit: material/pencil # é¡µé¢ç¼–è¾‘çš„å›¾æ ‡
    view: material/eye # é¡µé¢æŸ¥çœ‹æºä»£ç çš„å›¾æ ‡
    # annotation: material/arrow-right-circle # æç¤ºæŒ‰é’®çš„å›¾æ ‡ï¼Œè¯¦ç»†æ“ä½œè§ https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-1

extra: # é¢å¤–è®¾å®š
  alternate:
    - name: ç®€ä½“ä¸­æ–‡
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en
  version:
    provider: mike
    alias: true
  homepage: . # å·¦ä¸Šè§’å¾½æ ‡é“¾æ¥çš„åœ°å€ï¼ˆæ­¤å¤„ä¸ºä¸€ä¸ªç‚¹ï¼Œä¹Ÿå°±æ˜¯ä¸»é¡µï¼‰
  annotate: # å…è®¸ä»£ç å—éæ³¨é‡Šå†…çš„æç¤ºï¼Œæˆ‘ä¹Ÿä¸å¤ªæ‡‚ä»€ä¹ˆæ„æ€ï¼Œè²Œä¼¼æ˜¯å¯ä»¥åœ¨ä»£ç é‡Œé¢åŠ æ‚¬æµ®æç¤ºæ¡†ï¼Œè€Œä¸åªæ˜¯åœ¨æ³¨é‡Šä¸­ï¼ˆæ„Ÿè§‰è¿™æ ·ä¸å¥½ï¼Œè™½ç„¶æˆ‘ä¸ç”¨ï¼Œä½†ä¸èƒ½æ²¡æœ‰ï¼‰
    json: [.s2]
  social: # ç¤¾äº¤è”ç³»æ–¹å¼ï¼ˆé¡µé¢å³ä¸‹è§’å†…å®¹ï¼‰
    - icon: fontawesome/brands/github
      link: https://github.com/Xiaokang2022/tkintertools/
      name: Repository
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/tkintertools/
      name: PyPI
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/498105668
      name: å“”å“©å“”å“©
    - icon: fontawesome/solid/paper-plane
      link: mailto:2951256653@qq.com
      name: è”ç³»ä½œè€…

extra_javascript:
  - extra/js/shortcuts.js # ç»‘å®šå·¦å³é”®æ¢é¡µçš„é”®ç›˜å¿«æ·é”®
  - extra/js/tongji.baidu.js # ç™¾åº¦ç»Ÿè®¡è„šæœ¬
  - extra/js/mathjax.js # ä¿è¯æ•°å­¦è¡¨è¾¾å¼èƒ½æ­£ç¡®æ˜¾ç¤ºçš„è¿è¡Œæ—¶ç¯å¢ƒï¼ˆä¸‹é¢çš„ä¹Ÿæ˜¯ï¼‰
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - extra/css/extra.css # åŠ è½½è‡ªå®šä¹‰çš„æ ·å¼
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/css # è®¾ç½®å­—ä½“ï¼ˆéœé¹œæ–‡æ¥·ï¼‰

plugins:
  - search: # built-in
      lang:
        - zh
        - en
  - mike:
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      locale: zh
      timezone: Asia/Shanghai
  # - git-authors: # å½“é…ç½®ä¸å¥½ä¸‹æ–¹çš„ git-committers æ—¶å¯é‡‡ç”¨è¿™ä¸ª
  - git-committers:
      repository: Xiaokang2022/tkintertools-docs
      branch: main
      docs_path: 3.0/
      cache_dir: .cache/plugin/git-committers/3.0/
      token: !ENV ["GH_TOKEN"] # éœ€è¦è‡ªè¡Œåœ¨ç»ˆç«¯ä¸­è®¾ç½®ä¸´æ—¶ç¯å¢ƒå˜é‡ï¼Œå¼ºçƒˆä¸å»ºè®®æ˜¾å¼åœ°åœ¨æ­¤å¤„è®¾ç½® token
  - glightbox:
      background: none
  - statistics:
      codelines_per_minute: 10
      words_per_minute: 300
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

nav:
  - Back / è¿”å›ä¸»ç«™: https://Xiaokang2022.github.io/tkintertools

  - Home / ä¸»é¡µ: index.md

  - Tutorials / æ•™ç¨‹:
      - ç¬¬é›¶ç« ï¼šå‰è¨€: tutorials/0-0.md
      - ç¬¬ä¸€ç« ï¼šç®€å•ä½“éªŒ:
          - 1.1 å®‰è£… tkintertools: tutorials/1-1.md
          - 1.2 å®ç°ä¸€ä¸ªç®€å•çš„ç•Œé¢: tutorials/1-2.md
          - 1.3 æ¡†æ¶æ¦‚è¿° *: tutorials/1-3.md

      - ç¬¬äºŒç« ï¼šå®¹å™¨æ§ä»¶:
          - 2.1 çª—å£å®¹å™¨æ§ä»¶: tutorials/2-1.md
      #     - 2.2 ç”»å¸ƒå®¹å™¨æ§ä»¶: tutorials/2-2.md
      # - ç¬¬ä¸‰ç« ï¼šåŸºæœ¬æ§ä»¶:
      #     - 3.1 ä¿¡æ¯ç±»æ§ä»¶: tutorials/1-1.md
      #     - 3.2 åŠŸèƒ½ç±»æ§ä»¶: tutorials/1-1.md
      #     - 3.3 é«˜çº§æ§ä»¶: tutorials/1-1.md
      # - ç¬¬å››ç« ï¼šç•Œé¢å¸ƒå±€:
      #     - 4.1 Place: tutorials/1-1.md
      #     - 4.2 Pack å’Œ Grid: tutorials/1-1.md
      #     - 4.3 æ··åˆå¸ƒå±€: tutorials/1-1.md
      # - ç¬¬äº”ç« ï¼šå›¾åƒ:
      #     - 5.1 å›¾åƒåŸºç¡€æ“ä½œ: tutorials/1-1.md
      #     - 5.2 é«˜çº§æ“ä½œ: tutorials/1-1.md
      # - ç¬¬å…­ç« ï¼šåŠ¨ç”»:
      #     - 6.1 åŸºç¡€åŠ¨ç”»ç±»: tutorials/1-1.md
      #     - 6.2 é«˜çº§åŠ¨ç”»ç±»: tutorials/1-1.md
      #     - 6.3 æ§åˆ¶å™¨: tutorials/1-1.md
      # - ç¬¬ä¸ƒç« ï¼šé¢œè‰²:
      #     - 7.1 RGB: tutorials/1-1.md
      #     - 7.2 HSL: tutorials/1-1.md
      #     - 7.3 RGBA: tutorials/1-1.md
      # - ç¬¬å…«ç« ï¼šè‡ªå®šä¹‰å¼€å‘:
      #     - 8.1 è‡ªå®šä¹‰å®¹å™¨æ§ä»¶: tutorials/1-1.md
      #     - 8.2 è‡ªå®šä¹‰åŸºç¡€æ§ä»¶: tutorials/1-1.md
      #     - 8.3 è‡ªå®šä¹‰ç»„ä»¶: tutorials/1-1.md
      #     - 8.4 è‡ªå®šä¹‰æ§åˆ¶å™¨: tutorials/1-1.md
      #     - 8.5 è‡ªå®šä¹‰åŠ¨ç”»: tutorials/1-1.md
      # - ç¬¬ä¹ç« ï¼šæ‚é¡¹:
      #     - 9.1 æ··åˆ tkinter å¼€å‘: tutorials/1-1.md
      #     - 9.2 matplotlib æ‰©å±•åŒ…: tutorials/1-1.md
      #     - 9.3 3D æ‰©å±•åŒ…: tutorials/1-1.md
      #     - 9.4 Demos & Projects: tutorials/1-1.md

  - Documents / æ–‡æ¡£:
      - index: documents/index.md

      - ğŸ“¦ animation:
          - ğŸ“‘ animations: documents/animation/animations.md
          - ğŸ“‘ controllers: documents/animation/controllers.md

      - ğŸ“¦ color:
          - ğŸ“‘ colormap: documents/color/colormap.md
          - ğŸ“‘ hsl: documents/color/hsl.md
          - ğŸ“‘ rgb: documents/color/rgb.md

      - ğŸ“¦ core:
          - ğŸ“‘ constants: documents/core/constants.md
          - ğŸ“‘ containers: documents/core/containers.md
          - ğŸ“‘ virtual: documents/core/virtual.md

      - ğŸ“¦ standard:
          - ğŸ“‘ _auxiliary: documents/standard/_auxiliary.md
          - ğŸ“‘ dialogs: documents/standard/dialogs.md
          - ğŸ“‘ features: documents/standard/features.md
          - ğŸ“‘ images: documents/standard/images.md
          - ğŸ“‘ shapes: documents/standard/shapes.md
          - ğŸ“‘ texts: documents/standard/texts.md
          - ğŸ“‘ widgets: documents/standard/widgets.md

      - ğŸ“¦ style:
          - ğŸ“‘ manager: documents/style/manager.md
          - ğŸ“‘ parser: documents/style/parser.md

      - ğŸ“¦ theme:
          - ğŸ“‘ dark: documents/theme/dark.md
          - ğŸ“‘ light: documents/theme/light.md

      - ğŸ“¦ toolbox:
          - ğŸ“‘ enhanced: documents/toolbox/enhanced.md
          - ğŸ“‘ tools: documents/toolbox/tools.md

      - ğŸ“¦ mpl (Extension):
          - ğŸ“‘ constants: documents/mpl/constants.md
          - ğŸ“‘ main: documents/mpl/main.md

      - ğŸ“¦ three (Extension):
          - ğŸ“‘ constants: documents/three/constants.md
          - ğŸ“‘ engine: documents/three/engine.md
          - ğŸ“‘ geometries: documents/three/geometries.md
